# May amount of Users who can cooperate to craft Sandwiches.
maxAmountOfPicnicTableUsers = 1

# Duration of sandwich effects for each level in ticks (20 ticks = 1 second) (36000 = 30 minutes).
sandwichEffectDurationLevel1 = 36000

sandwichEffectDurationLevel2 = 36000

sandwichEffectDurationLevel3 = 36000

# Maximum number of concurrent sandwich effects allowed.
maxConcurrentSandwichEffects = 3

# Prevent eating another sandwich when the maximum number of effects are already active.
preventEatingWithMaxEffects = true

# Enable(true) or Disable(false) dynamic size changes of Pokemon. | Note: Disabling will turn Teensy and Humungo non functional & wild Pokemon wont spawn in different sizes! 
enableDynamicPokemonSizes = true

# Minimum and maximum scale modifiers for Pokemon sizes.
# These values act as multipliers to the default Pokemon size. For example:
# pokemonSizesMIN_SCALE = 0.8 means 80% of the normal size.
# pokemonSizesMAX_SCALE = 1.2 means 120% of the normal size.
pokemonSizesMIN_SCALE = 0.8

pokemonSizesMAX_SCALE = 1.2

# Settings for the Default scale distribution (when no sandwich powers are active).
# This determines the percentage chance of a Pokemon spawning with a certain size.
# defaultScale:  Represents a list of scales with associated probabilities.
[defaultScale]
XXXS = 0.006
XXS = 1.962
XS = 9.115
S = 19.501
M = 38.832
L = 19.501
XL = 9.115
XXL = 1.926
XXXL = 0.006

# Settings for Teensy Power scale distribution.
# This power drastically increases the chance of smaller Pokemon spawning.
# teensyScale: Represents a list of scales with associated probabilities.
[teensyScale.amplifier0]
XXXS = 0.781
XXS = 18.75
XS = 27.344
S = 31.25
[teensyScale.amplifier1]
XXXS = 1.042
XXS = 25.0
XS = 36.458
S = 37.5
[teensyScale.amplifier2]
XXXS = 1.563
XXS = 37.5
XS = 54.688
S = 6.25

# Settings for Humungo Power scale distribution.
# This power drastically increases the chance of larger Pokemon spawning.
# humungoScale: Represents a list of scales with associated probabilities.
[humungoScale.amplifier0]
L = 21.875
XL = 31.25
XXL = 27.344
XXXL = 18.75
[humungoScale.amplifier1]
L = 37.5
XL = 36.458
XXL = 25.0
XXXL = 1.042
[humungoScale.amplifier2]
L = 6.25
XL = 54.688
XXL = 37.5
XXXL = 1.563

# Settings for Encounter Power weight multipliers.
# Encounter Power forces a specific type of Pokémon to spawn, if possible.
# The levels increase the chance of forcing the specified type:
# Level 1: 50% chance to force spawn.
# Level 2: 75% chance to force spawn.
# Level 3: 100% chance to force spawn.
[encounterPower]
amplifier0 = 1.5
amplifier1 = 1.75
amplifier2 = 2.0
defaultMultiplier = 2.0
increasePerLevel = 0.5

# Settings for Sparkling Power additional shiny rolls.
# Sparkling Power increases the chance for Shiny Pokémon to appear by granting additional rolls.
# Each level adds a number of extra chances to find a shiny Pokemon:
# Level 1: 1 additional Shiny roll
# Level 2: 2 additional Shiny rolls
# Level 3: 3 additional Shiny rolls
[sparklingPower]
additionalRollsAmplifier0 = 1
additionalRollsAmplifier1 = 2
additionalRollsAmplifier2 = 3
baseAdditionalRolls = 3
extraRollsPerAmplifier = 1

# Settings for Exp. Point Power.
# Exp. Point Power increases the Experience received for defeating a specific type of Pokémon.
# The levels provide the following multipliers:
# Level 1: x1.1 bonus
# Level 2: x1.3 bonus
# Level 3: x1.5 bonus
[experiencePower]
additionalExpAmplifier0 = 1.1
additionalExpAmplifier1 = 1.3
additionalExpAmplifier2 = 1.5
baseAdditionalExp = 1.5
extraExpPerAmplifier = 0.5

# Settings for Catching Power.
# Catching Power increases the catch rate in battle.
# Level 1: x1.1 bonus.
# Level 2: x1.25 bonus.
# Level 3: x2 bonus.
[catchRatePower]
additionalCatchRateAmplifier0 = 1.1
additionalCatchRateAmplifier1 = 1.25
additionalCatchRateAmplifier2 = 2.0
baseAdditionalCatchRate = 2.0
extraCatchRatePerAmplifier = 0.5

# Settings for Item Drop Power.
# Item Drop Power increases the chance for a specific type of Pokémon to drop 1 additional item.
# The levels increase the chance of the extra drop:
# Level 1: 25% increase
# Level 2: 50% increase
# Level 3: 100% increase
[itemDropPower]
additionalItemDropAmplifier1 = 1.5
additionalItemDropAmplifier2 = 2.0
baseAdditionalItemDrop = 2.0
extraItemDropPerAmplifier = 0.5

# Enables or disables debug mode. When enabled, more detailed information is printed.
debugMode = false

# Enables or disables experimental settings. Turning this on might result in undocumented changes and should only be used in a development environment to compare results.
experimentalSettings = false

